- name: Update apt cache
  apt:
    update_cache: true
  become: true
  ignore_errors: true

- name: Install Monit
  apt:
    name: [ monit, jq, rrdtool ]
    state: present
  become: true

- name: Install Monit configs
  template:
    src: "{{ item.value.tmpl_src }}"
    dest: "{{ item.value.tmpl_dest }}"
    owner: "{{ item.value.tmpl_owner }}"
    group: "{{ item.value.tmpl_group }}"
    mode: "{{ item.value.tmpl_mode }}"
  with_dict: "{{ config_templates }}"
  become: true

- name: Copy Monit plugins
  copy:
    src: roles/monit/files/plugins
    dest: /etc/monit/
    mode: 0700
    owner: root
    group: root
  become: true

- name: Copy Monit handlers
  copy:
    src: roles/monit/files/handlers
    dest: /etc/monit/
    mode: 0700
    owner: root
    group: root
  become: true

- name: Copy Monit extra scripts
  copy:
    src: roles/monit/files/scripts
    dest: /etc/monit/
    mode: 0700
    owner: root
    group: root
  become: true

- name: Install cronjobs
  copy:
    src: roles/monit/files/crons/
    dest: /etc/cron.d/
    mode: 0644
    owner: root
    group: root
  become: true

- name: Install nginx config
  copy:
    src: roles/monit/files/nginx/
    dest: /etc/nginx/sites-enabled/
    mode: 0644
    owner: root
    group: root
  become: true

- name: Install nginx config drop-in
  copy:
    src: roles/monit/files/nginx.d/
    dest: /etc/nginx/conf.d/
    mode: 0644
    owner: root
    group: root
  become: true

- name: Create root path for Nginx
  file:
    path: /var/www/healthchecks
    state: directory
    mode: 0755
    owner: www-data
    group: www-data
  become: true

- name: Create root path for Letsencrypt challenge
  file:
    path: /var/www/acme
    state: directory
    mode: 0755
    owner: www-data
    group: www-data
  become: true

- name: Create root path for Letsencrypt certs
  file:
    path: /etc/ssl/acme
    state: directory
    mode: 0755
    owner: root
    group: root
  become: true

- name: Create directory for monit failure counters
  file:
    path: /var/lib/monit/counters
    state: directory
    mode: 0755
    owner: root
    group: root
  become: true

- name: Create RRD pool directory
  file:
    path: /var/lib/monit/rrd
    state: directory
    mode: 0755
    owner: root
    group: root
  become: true

- name: Test Nginx config
  command: "nginx -t"
  become: true

- name: Restart Nginx
  service:
    name: "nginx"
    state: restarted
  become: true

- name: Test Monit config
  command: "monit -t"
  become: true

- name: Restart Monit
  service:
    name: "monit"
    state: restarted
  become: true
