- name: Add sensu repository Gpg key
  command: "apt-key adv --fetch-keys https://sensu.global.ssl.fastly.net/apt/pubkey.gpg"
  become: true

- name: Add sensu repository
  template:
    src: roles/sensu/templates/repo.list.j2
    dest: "/etc/apt/sources.list.d/sensu.list"
  become: true

- name: Update apt cache
  apt:
    update_cache: true
  become: true
  ignore_errors: true

- name: Install Sensu
  apt: name={{ item }} state=installed
  with_items:
    - sensu
    - uchiwa
  become: true

- name: Restart all Sensu services
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - sensu-api
    - sensu-server
    - sensu-client
    - uchiwa
  become: true
