minutes: 1
hours: 60
days: 1440
weeks: 10080

checks_templates:
  dav_https:
    plugin: "check_https_certificate"
    argument: "dav.rcmd.space"
    interval: "{{ 10 * minutes }}"
    description: "Radicale SSL certificate"
    environment: "internal"
    notify: "telegram"
  site_https:
    plugin: "check_https_certificate"
    argument: "rcmd.space"
    interval: "{{ 10 * minutes }}"
    description: "Main Website SSL certificate"
    environment: "internal"
    notify: "telegram"
  blog_https:
    plugin: "check_https_certificate"
    argument: "blog.rcmd.space"
    interval: "{{ 10 * minutes }}"
    description: "Blog Website SSL certificate"
    environment: "internal"
    notify: "telegram"
  transmission_https:
    plugin: "check_https_certificate"
    argument: "transmission.it-the-drote.tk"
    interval: "{{ 10 * minutes }}"
    description: "Transmission SSL certificate"
    environment: "internal"
    notify: "telegram"
  xmpp_server_ssl:
    plugin: "check_xmpp_certificate"
    argument: "it-the-drote.tk"
    interval: "{{ 10 * minutes }}"
    description: "XMPP server TLS certificate"
    environment: "external"
    notify: "telegram"
  xmpp_server_alive:
    plugin: "check_systemd_service"
    argument: "prosody.service"
    interval: "{{ 1 * minutes }}"
    description: "XMPP server"
    environment: "external"
    notify: "telegram"
  postfix_alive:
    plugin: "check_systemd_service"
    argument: "postfix.service"
    interval: "{{ 1 * minutes }}"
    description: "Postfix"
    environment: "internal"
    notify: "telegram"
  kernel_version:
    plugin: "check_kernel_version"
    argument: ""
    interval: "{{ 8 * hours }}"
    description: "Linux Kernel Version"
    environment: "internal"
    notify: "telegram"
  free_space:
    plugin: "check_disk_space"
    argument: "/dev/vda1"
    interval: "{{ 3 * minutes }}"
    description: "Free space on disk"
    environment: "external"
    notify: "telegram"
  loadavg:
    plugin: "plot_loadavg"
    argument: ""
    interval: "{{ 1 * minutes }}"
    description: "Load average for 5 minutes"
    environment: "external"
    notify: "dummy"
  memory_usage:
    plugin: "plot_memory_usage"
    argument: ""
    interval: "{{ 1 * minutes }}"
    description: "Memory usage"
    environment: "external"
    notify: "dummy"
  api_website:
    plugin: "check_http_ping"
    argument: "https://api.rcmd.space/hooks/healthcheck"
    interval: "{{ 1 * minutes }}"
    description: "RCMD API website"
    environment: "internal"
    notify: "telegram"
  api_https:
    plugin: "check_https_certificate"
    argument: "api.rcmd.space"
    interval: "{{ 10 * minutes }}"
    description: "API HTTPS certificate"
    environment: "internal"
    notify: "telegram"
  traccar:
    plugin: "check_traccar_logs"
    argument: "{{ traccar.device_id }}"
    interval: "{{ 10 * minutes }}"
    description: "Check traccar reported location"
    environment: "internal"
    notify: "traccar"