minutes: 1
hours: 60
days: 1440
weeks: 10080

checks_templates:
  bullshit:
    plugin: "check_file"
    argument: "/tmp/bullshit"
    interval: "{{ 1 * minutes }}"
    description: "Bullshit file"
    environment: "external"
    notify: "telegram"
  nextcloud_https:
    plugin: "check_https_certificate"
    argument: "cloud.it-the-drote.tk"
    interval: "{{ 1 * days }}"
    description: "Nextcloud HTTPS certificate"
    environment: "internal"
    notify: "telegram"
  transmission_https:
    plugin: "check_https_certificate"
    argument: "transmission.it-the-drote.tk"
    interval: "{{ 1 * days }}"
    description: "Transmission HTTPS certificate"
    environment: "internal"
    notify: "telegram"
  xmpp_server_ssl:
    plugin: "check_xmpp_certificate"
    argument: "it-the-drote.tk"
    interval: "{{ 1 * days }}"
    description: "XMPP server TLS certificate"
    environment: "external"
    notify: "telegram"
  xmpp_server_alive:
    plugin: "check_systemd_service"
    argument: "prosody.service"
    interval: "{{ 1 * minutes }}"
    description: "XMPP server"
    environment: "external"
    notify: "telegram"
  apps_yatranslate_alive:
    plugin: "check_systemd_service"
    argument: "apps-yatranslate.service"
    interval: "{{ 1 * minutes }}"
    description: "Yandex.Translate Bot"
    environment: "internal"
    notify: "telegram"
  avitorss_proxy_alive:
    plugin: "check_docker_container"
    argument: "squidy"
    interval: "{{ 1 * minutes }}"
    description: "Avito2rss Proxy"
    environment: "external"
    notify: "telegram"
  postfix_alive:
    plugin: "check_systemd_service"
    argument: "postfix.service"
    interval: "{{ 1 * minutes }}"
    description: "Postfix"
    environment: "internal"
    notify: "telegram"
  kernel_version:
    plugin: "check_kernel_version"
    argument: ""
    interval: "{{ 1 * days }}"
    description: "Linux Kernel Version"
    environment: "internal"
    notify: "telegram"
  free_space:
    plugin: "check_disk_space"
    argument: "/dev/vda1"
    interval: "{{ 10 * minutes }}"
    description: "Free space on disk"
    environment: "external"
    notify: "telegram"
  main_website:
    plugin: "check_http_ping"
    argument: "http://it-the-drote.tk/ping"
    interval: "{{ 1 * minutes }}"
    description: "IT The Drote website"
    environment: "external"
    notify: "telegram"
  api_website:
    plugin: "check_http_ping"
    argument: "http://api.it-the-drote.tk/ping"
    interval: "{{ 1 * minutes }}"
    description: "IT The Drote API website"
    environment: "internal"
    notify: "telegram"
  api_https:
    plugin: "check_https_certificate"
    argument: "api.it-the-drote.tk"
    interval: "{{ 1 * days }}"
    description: "API HTTPS certificate"
    environment: "internal"
    notify: "telegram"
  nextcloud_website:
    plugin: "check_http_ping"
    argument: "https://cloud.it-the-drote.tk/status.php"
    interval: "{{ 1 * minutes }}"
    description: "Nextcloud services"
    environment: "external"
    notify: "telegram"
  mysql:
    plugin: "check_mysql"
    argument: ""
    interval: "{{ 1 * minutes }}"
    description: "MySQL"
    environment: "external"
    notify: "telegram"
  orphaned_files:
    plugin: "check_orphaned_files"
    argument: ""
    interval: "{{ 1 * minutes }}"
    description: "Orphaned files"
    environment: "internal"
    notify: "telegram"
