minutes: 1
hours: 60
days: 1440
weeks: 10080
rrd_directory: "/var/lib/monit/rrd"
rrd_graphs_directory: "/var/www/healthchecks/builds/operations"

checks_templates:
  - name: "dav_https"
    state: "touch"
    plugin: "check_https_certificate"
    type: "alert"
    argument: "dav.rcmd.space"
    interval: "{{ 10 * minutes }}"
    description: "Radicale SSL certificate"
    environment: "internal"
    notify: "telegram"
  - name: "site_https"
    state: "touch"
    plugin: "check_https_certificate"
    type: "alert"
    argument: "rcmd.space"
    interval: "{{ 10 * minutes }}"
    description: "Main Website SSL certificate"
    environment: "internal"
    notify: "telegram"
  - name: "blog_https"
    state: "touch"
    plugin: "check_https_certificate"
    type: "alert"
    argument: "blog.rcmd.space"
    interval: "{{ 10 * minutes }}"
    description: "Blog Website SSL certificate"
    environment: "internal"
    notify: "telegram"
  - name: "transmission_https"
    state: "touch"
    plugin: "check_https_certificate"
    type: "alert"
    argument: "transmission.it-the-drote.tk"
    interval: "{{ 10 * minutes }}"
    description: "Transmission SSL certificate"
    environment: "internal"
    notify: "telegram"
  - name: "xmpp_server_ssl"
    state: "touch"
    plugin: "check_xmpp_certificate"
    type: "alert"
    argument: "it-the-drote.tk"
    interval: "{{ 10 * minutes }}"
    description: "XMPP server TLS certificate"
    environment: "external"
    notify: "telegram"
  - name: "xmpp_server_alive"
    state: "touch"
    plugin: "check_systemd_service"
    type: "alert"
    argument: "prosody.service"
    interval: "{{ 1 * minutes }}"
    description: "XMPP server"
    environment: "external"
    notify: "telegram"
  - name: "postfix_alive"
    state: "touch"
    plugin: "check_systemd_service"
    type: "alert"
    argument: "postfix.service"
    interval: "{{ 1 * minutes }}"
    description: "Postfix"
    environment: "internal"
    notify: "telegram"
  - name: "kernel_version"
    state: "touch"
    plugin: "check_kernel_version"
    type: "alert"
    argument: ""
    interval: "{{ 8 * hours }}"
    description: "Linux Kernel Version"
    environment: "internal"
    notify: "telegram"
  - name: "free_space"
    state: "touch"
    plugin: "check_disk_space"
    type: "alert"
    argument: "/dev/vda1"
    interval: "{{ 3 * minutes }}"
    description: "Free space on disk"
    environment: "external"
    notify: "telegram"
  - name: "loadavg"
    state: "absent"
    plugin: "plot_loadavg"
    type: "graph"
    argument: "{{ rrd_directory }}/loadavg.rrd"
    interval: "{{ 1 * minutes }}"
    description: "Load average for 5 minutes"
    environment: "external"
    notify: "dummy"
  - name: "memory_usage"
    state: "absent"
    plugin: "plot_memory_usage"
    type: "graph"
    argument: "{{ rrd_directory }}/memory_usage.rrd"
    interval: "{{ 1 * minutes }}"
    description: "Memory usage"
    environment: "external"
    notify: "dummy"
  - name: "api_website"
    state: "absent"
    plugin: "check_http_ping"
    type: "alert"
    argument: "https://api.rcmd.space/hooks/healthcheck"
    interval: "{{ 1 * minutes }}"
    description: "RCMD API website"
    environment: "internal"
    notify: "telegram"
  - name: "api_https"
    state: "touch"
    plugin: "check_https_certificate"
    type: "alert"
    argument: "api.rcmd.space"
    interval: "{{ 10 * minutes }}"
    description: "API HTTPS certificate"
    environment: "internal"
    notify: "telegram"
  - name: "traccar"
    state: "touch"
    plugin: "check_traccar_logs"
    type: "alert"
    argument: "{{ traccar.device_id }}"
    interval: "{{ 10 * minutes }}"
    description: "Check traccar reported location"
    environment: "internal"
    notify: "traccar"
  - name: "net_conns"
    state: "absent"
    plugin: "plot_established_connections"
    type: "graph"
    argument: "{{ rrd_directory }}/net_conns.rrd"
    interval: "{{ 1 * minutes }}"
    description: "Established network connections"
    environment: "external"
    notify: "dummy"
  - name: "swap_usage"
    state: "absent"
    plugin: "plot_swap_usage"
    type: "graph"
    argument: "{{ rrd_directory }}/swap_usage.rrd"
    interval: "{{ 1 * minutes }}"
    description: "Swap usage in percents"
    environment: "external"
    notify: "dummy"
  - name: "spotify_clicks"
    state: "absent"
    plugin: "plot_spotify_clicks"
    type: "graph"
    argument: "{{ rrd_directory }}/spotify_clicks.rrd"
    interval: "{{ 1 * days }}"
    description: "Spotify link clicks daily"
    environment: "external"
    notify: "dummy"