minutes: 1
hours: 60
days: 1440
weeks: 10080

checks_templates:
  bullshit:
    plugin: "check_file"
    argument: "/tmp/bullshit"
    interval: "{{ 1 * minutes }}"
    notify: "telegram"
  nextcloud_https:
    plugin: "check_https_certificate"
    argument: "cloud.it-the-drote.tk"
    interval: "{{ 1 * days }}"
    notify: "telegram"
  xmpp_server_ssl:
    plugin: "check_xmpp_certificate"
    argument: "it-the-drote.tk"
    interval: "{{ 1 * days }}"
    notify: "telegram"
  xmpp_server_alive:
    plugin: "check_systemd_service"
    argument: "prosody.service"
    interval: "{{ 1 * minutes }}"
    notify: "telegram"
  apps_yatranslate_alive:
    plugin: "check_systemd_service"
    argument: "apps-yatranslate.service"
    interval: "{{ 1 * minutes }}"
    notify: "telegram"
  avitorss_proxy_alive:
    plugin: "check_docker_container"
    argument: "squidy"
    interval: "{{ 1 * minutes }}"
    notify: "telegram"
  postfix_alive:
    plugin: "check_systemd_service"
    argument: "postfix.service"
    interval: "{{ 1 * minutes }}"
    notify: "telegram"
  kernel_version:
    plugin: "check_kernel_version"
    argument: ""
    interval: "{{ 1 * days }}"
    notify: "telegram"
