minutes: 1
hours: 60
days: 1440
weeks: 10080

checks_templates:
  - name: "dav_https"
    state: "present"
    plugin: "check_https_certificate"
    type: "alert"
    argument: "dav.rcmd.space"
    interval: "{{ 10 * minutes }}"
    description: "Radicale SSL certificate"
    environment: "internal"
    notify: "squadcast"
  - name: "site_https"
    state: "present"
    plugin: "check_https_certificate"
    type: "alert"
    argument: "rcmd.space"
    interval: "{{ 10 * minutes }}"
    description: "Main Website SSL certificate"
    environment: "internal"
    notify: "squadcast"
  - name: "blog_https"
    state: "present"
    plugin: "check_https_certificate"
    type: "alert"
    argument: "blog.rcmd.space"
    interval: "{{ 10 * minutes }}"
    description: "Blog Website SSL certificate"
    environment: "internal"
    notify: "squadcast"
  - name: "transmission_https"
    state: "absent"
    plugin: "check_https_certificate"
    type: "alert"
    argument: "transmission.it-the-drote.tk"
    interval: "{{ 10 * minutes }}"
    description: "Transmission SSL certificate"
    environment: "internal"
    notify: "squadcast"
  - name: "xmpp_server_ssl"
    state: "present"
    plugin: "check_xmpp_certificate"
    type: "alert"
    argument: "it-the-drote.tk"
    interval: "{{ 10 * minutes }}"
    description: "XMPP server TLS certificate"
    environment: "external"
    notify: "squadcast"
  - name: "xmpp_server_alive"
    state: "present"
    plugin: "check_systemd_service"
    type: "alert"
    argument: "prosody.service"
    interval: "{{ 1 * minutes }}"
    description: "XMPP server"
    environment: "external"
    notify: "squadcast"
  - name: "postfix_alive"
    state: "present"
    plugin: "check_systemd_service"
    type: "alert"
    argument: "postfix.service"
    interval: "{{ 1 * minutes }}"
    description: "Postfix"
    environment: "internal"
    notify: "squadcast"
  - name: "kernel_version"
    state: "present"
    plugin: "check_kernel_version"
    type: "alert"
    argument: ""
    interval: "{{ 8 * hours }}"
    description: "Linux Kernel Version"
    environment: "internal"
    notify: "squadcast"
  - name: "free_space"
    state: "present"
    plugin: "check_disk_space"
    type: "alert"
    argument: "/dev/vda1"
    interval: "{{ 3 * minutes }}"
    description: "Free space on disk"
    environment: "external"
    notify: "squadcast"
  - name: "api_website"
    state: "present"
    plugin: "check_http_ping"
    type: "alert"
    argument: "https://api.rcmd.space/hooks/healthcheck"
    interval: "{{ 1 * minutes }}"
    description: "RCMD API website"
    environment: "internal"
    notify: "squadcast"
  - name: "api_https"
    state: "present"
    plugin: "check_https_certificate"
    type: "alert"
    argument: "api.rcmd.space"
    interval: "{{ 10 * minutes }}"
    description: "API HTTPS certificate"
    environment: "internal"
    notify: "squadcast"
  - name: "traccar"
    state: "present"
    plugin: "check_traccar_logs"
    type: "alert"
    argument: "{{ traccar.device_id }}"
    interval: "{{ 10 * minutes }}"
    description: "Check traccar reported location"
    environment: "internal"
    notify: "traccar"
  - name: "caldav_backups"
    state: "present"
    plugin: "check_duplicity_backup"
    type: "alert"
    argument: "file:///var/storage/wastebox/Backups/radicale/"
    interval: "{{ 1 * days }}"
    description: "CalDAV backups"
    environment: "internal"
    notify: "squadcast"
  - name: "website_backups"
    state: "present"
    plugin: "check_duplicity_backup"
    type: "alert"
    argument: "file:///var/storage/wastebox/Backups/websites/"
    interval: "{{ 1 * days }}"
    description: "Website backups"
    environment: "internal"
    notify: "squadcast"