- name: Install checks
  template:
    src: "roles/checks/templates/check.cfg.j2"
    dest: "/etc/monit/conf.d/{{ item.name }}.cfg"
    owner: "root"
    group: "root"
    mode: 0600
  loop: "{{ checks_templates }}"
  no_log: true
  become: true

- name: Clean up disabled checks
  file:
    path: "/etc/monit/conf.d/{{ item.name }}.cfg"
    state: "{{ 'touch' if item.state == 'present' else 'absent' }}"
  loop: "{{ checks_templates }}"
  no_log: true
  become: true

- name: Test Monit config
  command: "monit -t"
  become: true

- name: Restart Monit
  service:
    name: "monit"
    state: restarted
  become: true
