- name: Install checks
  template:
    src: "roles/checks/templates/check.cfg.j2"
    dest: "/etc/monit/conf.d/{{ item.name }}.cfg"
    owner: "root"
    group: "root"
    mode: 0600
  loop: "{{ checks_templates }}"
  no_log: true
  become: true

- name: Clean up disabled checks
  file:
    path: "/etc/monit/conf.d/{{ item.name }}.cfg"
    state: "{{ item.state }}"
  loop: "{{ checks_templates }}"
  no_log: true
  become: true

- name: Create RRD files
  command: |
    bash -c 'test -f {{ rrd_directory }}/{{ item.name }}.rrd || rrdtool create {{ rrd_directory }}/{{ item.name }}.rrd \
    --step {{ item.interval | int * 60 }} \
    DS:{{ item.name }}:GAUGE:{{ item.interval | int * 120 }}:0:U \
    RRA:AVERAGE:0.5:12:744'
  loop: "{{ checks_templates }}"
  when: item.type == "graph" and item.state != absent
  become: true

- name: Plot RRD graphs
  cron:
    name: "Plot graphs for {{ item.name }}"
    state: "{{ 'present' if item.state == 'touch' }}"
    minute: "*/5"
    job: >
      rrdtool graph {{ rrd_graphs_directory }}/{{ item.name }}.png
      -w 400 -h 200
      DEF:{{ item.name }}={{ rrd_directory }}/{{ item.name }}.rrd:{{ item.name }}:AVERAGE
      LINE2:{{ item.name }}#0000ff:"{{ item.description }}"
  loop: "{{ checks_templates }}"
  when: item.type == "graph"
  become: true

- name: Draw HTML page
  template:
    src: "roles/checks/templates/graphs.html.j2"
    dest: "{{ rrd_graphs_directory }}/index.html"
    owner: "www-data"
    group: "www-data"
    mode: 0600
  become: true

- name: Test Monit config
  command: "monit -t"
  become: true

- name: Restart Monit
  service:
    name: "monit"
    state: restarted
  become: true
